# Site settings
title: Full STEAM Ahead
baseurl: ""

paginate: 15
paginate_path: /page:num/

#email:
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# Build settings
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
